import type { Dirent } from "node:fs";
import { readdir } from "node:fs/promises";
import { isAbsolute, relative, resolve, sep } from "node:path";

type JsonObject = Record<string, unknown>;

type CatalogEntry = JsonObject & {
  resourceUrl: string;
};

const root = resolve(import.meta.dir, "..");
const themeRoot = resolve(root, "theme");
const indexPath = resolve(root, "index.json");
const readmePath = resolve(root, "README.md");

const requiredManifestFields = [
  "id",
  "name",
  "version",
  "author",
  "description",
  "entry",
] as const;

function fail(message: string): never {
  throw new Error(message);
}

function isJsonObject(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function requiredString(
  manifest: JsonObject,
  field: string,
  manifestPath: string,
): string {
  const value = manifest[field];
  if (typeof value !== "string" || value.trim().length === 0) {
    fail(`${manifestPath}: ${field} must be a non-empty string`);
  }
  return value;
}

function packageFile(
  themePath: string,
  filePath: string,
  manifestPath: string,
): string {
  const resolvedPath = resolve(themePath, filePath);
  const packageRelativePath = relative(themePath, resolvedPath);
  if (
    isAbsolute(packageRelativePath) ||
    packageRelativePath === ".." ||
    packageRelativePath.startsWith(`..${sep}`)
  ) {
    fail(`${manifestPath}: file path escapes the theme directory: ${filePath}`);
  }
  return resolvedPath;
}

async function readManifest(manifestPath: string): Promise<JsonObject> {
  try {
    const manifest = JSON.parse(await Bun.file(manifestPath).text()) as unknown;
    if (!isJsonObject(manifest)) {
      fail(`${manifestPath}: manifest must be a JSON object`);
    }
    return manifest;
  } catch (error) {
    if (error instanceof SyntaxError) {
      fail(`${manifestPath}: invalid JSON (${error.message})`);
    }
    throw error;
  }
}

async function loadThemes(): Promise<CatalogEntry[]> {
  let themeDirectories: Dirent[];
  try {
    themeDirectories = await readdir(themeRoot, { withFileTypes: true });
  } catch {
    fail(`theme directory not found: ${themeRoot}`);
  }

  themeDirectories = themeDirectories
    .filter((entry) => entry.isDirectory())
    .sort((left, right) =>
      left.name < right.name ? -1 : left.name > right.name ? 1 : 0,
    );
  const themes: CatalogEntry[] = [];
  const seenIds = new Set<string>();

  for (const themeDirectory of themeDirectories) {
    const themePath = resolve(themeRoot, themeDirectory.name);
    const manifestPath = resolve(themePath, "manifest.json");
    if (!(await Bun.file(manifestPath).exists())) {
      fail(`${themePath}: missing manifest.json`);
    }

    const manifest = await readManifest(manifestPath);
    for (const field of requiredManifestFields) {
      requiredString(manifest, field, manifestPath);
    }

    const id = manifest.id as string;
    if (seenIds.has(id)) {
      fail(`duplicate theme id: ${id}`);
    }
    seenIds.add(id);

    const entry = manifest.entry as string;
    const entryPath = packageFile(themePath, entry, manifestPath);
    if (!(await Bun.file(entryPath).exists())) {
      fail(`${manifestPath}: entry file not found: ${entry}`);
    }

    const preview = manifest.preview;
    if (preview !== undefined) {
      if (typeof preview !== "string" || preview.trim().length === 0) {
        fail(`${manifestPath}: preview must be a non-empty string`);
      }
      const previewPath = packageFile(themePath, preview, manifestPath);
      if (!(await Bun.file(previewPath).exists())) {
        fail(`${manifestPath}: preview file not found: ${preview}`);
      }
    }

    if (
      manifest.controlsThemeColor !== undefined &&
      typeof manifest.controlsThemeColor !== "boolean"
    ) {
      fail(`${manifestPath}: controlsThemeColor must be a boolean`);
    }

    themes.push({
      ...manifest,
      resourceUrl: relative(root, themePath).split(sep).join("/"),
    });
  }

  return themes.sort((left, right) =>
    left.id < right.id ? -1 : left.id > right.id ? 1 : 0,
  );
}

function renderIndex(themes: CatalogEntry[]): string {
  return `${JSON.stringify({ version: 1, themes }, null, 2)}\n`;
}

function markdownText(value: string): string {
  return value.replace(/\s+/g, " ").trim().replaceAll("|", "\\|");
}

function renderReadme(themes: CatalogEntry[]): string {
  const lines = [
    "# MicYou Themes",
    "",
    "<!-- Generated by scripts/generate_catalog.ts. Do not edit manually. -->",
    "",
    "MicYou 的主题目录与主题包仓库。",
    "",
    "## 仓库结构",
    "",
    "```text",
    "/",
    "├── index.json                 # 自动生成的主题清单",
    "└── theme/",
    "    └── <theme-id>/",
    "        ├── manifest.json      # 主题元数据（生成来源）",
    "        ├── theme.css          # 主题样式",
    "        └── preview.png        # 可选预览图",
    "```",
    "",
    "`index.json` 和本节下面的主题列表均由各主题目录中的 `manifest.json` 自动生成。",
    "",
    "每个主题目录至少包含 `manifest.json` 和 CSS 入口文件，预览图是可选的。",
    "",
    "主题清单中的 `controlsThemeColor` 用于声明主题是否接管 MicYou 的主题色生成器：",
    "",
    "- `true` 或未填写：主题 CSS 可以接管主题色设置。",
    "- `false`：主题只调整布局、形状等视觉细节，应用继续使用系统/预置主题色。",
    "",
    "## 当前主题",
    "",
    "| 预览 | ID | 名称 | 描述 | 版本 | 作者 | 主题色 |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  ];

  if (themes.length === 0) {
    lines.push("| — | — | — | 暂无主题 | — | — | — |");
  } else {
    for (const theme of themes) {
      const colorNote =
        theme.controlsThemeColor === false ? "不接管主题色" : "接管主题色";
      const preview =
        typeof theme.preview === "string"
          ? `![${markdownText(theme.name as string)}](${theme.resourceUrl}/${theme.preview})`
          : "—";
      lines.push(
        `| ${preview} | \`${theme.id}\` | ${markdownText(theme.name as string)} | ${markdownText(theme.description as string)} | ${markdownText(theme.version as string)} | ${markdownText(theme.author as string)} | ${colorNote} |`,
      );
    }
  }

  lines.push(
    "",
    "## 生成",
    "",
    "修改或新增主题后，在仓库根目录执行：",
    "",
    "```sh",
    "bun run generate",
    "```",
    "",
    "脚本会校验 manifest、入口 CSS 和预览图，并更新 `index.json` 与 `README.md`。",
    "主分支上的主题变更也会由 GitHub Actions 自动执行该脚本。",
    "",
    "## 安全说明",
    "",
    "安装主题时只下载清单和 CSS，CSS 会在独立的主题包样式节点中应用。主题包不支持脚本，仓库中的主题内容不会执行任意代码。",
    "",
  );
  return lines.join("\n");
}

async function writeOrCheck(
  path: string,
  content: string,
  check: boolean,
): Promise<boolean> {
  const file = Bun.file(path);
  const current = (await file.exists()) ? await file.text() : undefined;
  if (current === content) {
    return false;
  }

  if (check) {
    console.log(`outdated: ${relative(root, path)}`);
    return true;
  }

  await Bun.write(path, content);
  console.log(`updated: ${relative(root, path)}`);
  return true;
}

async function main(): Promise<number> {
  const check = Bun.argv.includes("--check");
  const themes = await loadThemes();
  const changed = [
    await writeOrCheck(indexPath, renderIndex(themes), check),
    await writeOrCheck(readmePath, renderReadme(themes), check),
  ];
  return check && changed.some(Boolean) ? 1 : 0;
}

main()
  .then((exitCode) => {
    process.exitCode = exitCode;
  })
  .catch((error: unknown) => {
    console.error(
      `error: ${error instanceof Error ? error.message : String(error)}`,
    );
    process.exitCode = 1;
  });
